server:
  port: 5678
spring:
  application:
    name: flask-service

sidecar:
  hostname: localhost
  ip-address: 127.0.0.1
  port: 5000
  health-uri: http://${sidecar.hostname}:${sidecar.port}/health.json
  home-page-uri: http://${sidecar.hostname}:${sidecar.port}/ 
  
